version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  auth-service:
    build: ./myonsite-core/auth-service
    env_file: .env
    ports:
      - "5001:5001"

  user-service:
    build: ./myonsite-core/user-service
    env_file: .env
    ports:
      - "5002:5002"

  chat-service:
    build: ./myonsite-core/chat-service
    env_file: .env
    ports:
      - "5003:5003"
    depends_on:
      - ai-orchestration-service
      - document-service

  ai-orchestration-service:
    build: ./myonsite-core/ai-orchestration-service
    env_file: .env
    ports:
      - "5004:5004"
    depends_on:
      - mcp-service

  document-service:
    build: ./myonsite-core/document-service
    env_file: .env
    ports:
      - "5005:5005"

  approval-service:
    build: ./myonsite-core/approval-service
    env_file: .env
    ports:
      - "5006:5006"

  notification-service:
    build: ./myonsite-core/notification-service
    env_file: .env
    ports:
      - "5007:5007"

  mcp-service:
    build: ./myonsite-core/mcp-service
    env_file: .env
    ports:
      - "5008:5008"

  frontend:
    build: ./myonsite-core/frontend
    env_file: .env
    ports:
      - "8501:8501"
    depends_on:
      - chat-service

volumes:
  pgdata:
